import{i as g}from"./assets/vendor-ad859c2f.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const p={time:document.querySelector(".time")};function y(){const t=new Date,e=t.getDate().toString().padStart(2,"0"),i=["January","February","March","April","May","June","July","August","September","October","November","December"][t.getMonth()],r=t.getFullYear(),s=t.getHours().toString().padStart(2,"0"),a=t.getMinutes().toString().padStart(2,"0"),f=t.getSeconds().toString().padStart(2,"0");return`${e} ${i} ${r}, ${s}:${a}:${f}`}function d(){p.time.textContent=y()}setInterval(d,1e3);d();function u(t,e){const o=JSON.stringify(e);localStorage.setItem(t,o)}function h(t){const e=localStorage.getItem(t);try{return JSON.parse(e)}catch{return null}}function l(t){const e={high:3,medium:2,low:1};return t.sort((o,i)=>e[i.priority]-e[o.priority])}function b(t){switch(t){case"high":return"#F08080";case"medium":return"#FFFACD";case"low":return"#D3D3D3";default:return"#fff"}}function m({text:t,priority:e,id:o}){return`
      <li class="todos-item" style="background-color: ${b(e)}">
        <span class="todos-text">${t}</span>
        <span class="todos-info">${e}</span>
        <div class="btn-wrapper">
          <button id="edit" class="edit" data-id="${o}" type="button">&#9998;</button>
          <button id="done" class="done" data-id="${o}" type="button">&#10003;</button>
          <button id="delete" class="delete" data-id="${o}" type="button">&#10007;</button>
        </div>
      </li>`}const c={form:document.querySelector(".js-form"),todoList:document.querySelector(".todos-list"),select:document.querySelector(".todos-select")};let n=h("todos")||[];c.form.addEventListener("submit",t=>{t.preventDefault();const e=t.currentTarget.elements.todos.value.trim(),o=t.currentTarget.elements.select.value;if(!e||!o)return g.error({title:"Error",message:"Please enter both a task and a priority",position:"topRight"});const i={id:Date.now(),text:e,priority:o};n.push(i),n=l(n),u("todos",n),c.todoList.innerHTML=n.map(m).join(""),t.currentTarget.reset()});document.addEventListener("DOMContentLoaded",()=>{n.length&&(n=l(n),c.todoList.innerHTML=n.map(m).join(""))});c.todoList.addEventListener("click",t=>{if(t.target.nodeName!=="BUTTON")return;const e=Number(t.target.dataset.id);if(t.target.id==="delete"&&(n=n.filter(o=>o.id!==e),u("todos",n),t.target.closest(".todos-item").remove()),t.target.id==="done"){const o=t.target.closest(".todos-item");o.querySelector(".todos-text").style.textDecoration="line-through"}t.target.id==="edit"&&t.target.closest(".todos-item")});
//# sourceMappingURL=commonHelpers.js.map
